version: "3"
services:
  swoole:
    build:
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
    environment:
      - SWOOLE_HTTP_HOST=0.0.0.0
      - SWOOLE_HTTP_PORT=80
      - DATABASE_URL=postgres://postgres:postgres@db:5432/shop
      - APP_ENV=local
      - APP_DEBUG=true

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
